In [2]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 8])   ####  List 
print(a)

print(np.arange(10))

print(np.append(a,[1,2]))

a=np.delete(a,1)
print(a)

a=np.sort(a)
print(a)

[0 1 2 3 4 8]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 8 1 2]
[0 2 3 4 8]
[0 2 3 4 8]


In [3]:
ex = np.array([[[1,2,3,4], [5,6,7,8]],
[[9,10,11,12], [13,14,15,16]],
[[17,18,19,20], [21,22,23,24]]])

print(ex)

print(ex.ndim)
print(ex.size)
print(ex.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3
24
(3, 2, 4)


In [5]:
ex=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

print(ex)
print(ex.reshape(3,2,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [7]:
ex=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(ex.shape)

ex2=ex[np.newaxis]
print(ex2.shape)
print(ex2)

ex3=ex[:, np.newaxis]
print(ex3.shape)
print(ex3)

ex4=np.expand_dims(ex, axis=0)
print(ex4.shape)
print(ex4)


(11,)
(1, 11)
[[ 1  2  3  4  5  6  7  8  9 10 11]]
(11, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(1, 11)
[[ 1  2  3  4  5  6  7  8  9 10 11]]


In [9]:
a1=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22],[23,24,25,26],[27,28,29,30]])

print(a1)
print(a1[a1>=13])
a2=(a1>=10)
print(a1[a2])
print(a1[a1%2==1])
print(a1[a1%2==0])

a3=np.array([1,2,3,4,5,6,7,8,9,10])
aa=a3[5:7]
print(aa)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[11 13 15 17 19 21 23 25 27 29]
[12 14 16 18 20 22 24 26 28 30]
[6 7]


In [ ]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print(a1)
print(a2)
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))
print()
print()
print()

x1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
